// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxLsNyf7eU7LY2Q7djslkIao7jO3l9OXA',
    appId: '1:594129198668:web:03c60b54702d8f876e1ee9',
    messagingSenderId: '594129198668',
    projectId: 'restohub-b6c1b',
    authDomain: 'restohub-b6c1b.firebaseapp.com',
    storageBucket: 'restohub-b6c1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5GNMw6znnaBK247dtYrdNkMwHIsFVfA',
    appId: '1:594129198668:android:90dbdcfe5207bfff6e1ee9',
    messagingSenderId: '594129198668',
    projectId: 'restohub-b6c1b',
    storageBucket: 'restohub-b6c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYe_rbq3cFpf4il3jPFn6c57tlw-1xj0',
    appId: '1:594129198668:ios:f53f50e08365e8606e1ee9',
    messagingSenderId: '594129198668',
    projectId: 'restohub-b6c1b',
    storageBucket: 'restohub-b6c1b.appspot.com',
    iosClientId: '594129198668-49b3bg9j4eqpjdar3jqicqe0nutm0539.apps.googleusercontent.com',
    iosBundleId: 'com.example.restohub',
  );
}
